### ISSUE TITLE
12. As a user, I want to view a list of my shopping list items in order of how soon I am likely to need to buy each of them again

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-5-smart-shopping-list#13]
Possible item states are as follows:

* Need to buy Soon (fewer than 7 days)
* Need to buy Kind of soon (between 7 & 30 days)
* Need to buy Not soon (more than 30 days)
* Inactive (only 1 purchase in the database or the purchase is really out of date [2x the estimate])

AC:

* Items in the list are shown visually grouped in the following order: Soon, Kind of soon, Not soon, Inactive
* Within each grouping, items should be sorted by the estimated number of days until next purchase
* Items with the same number of estimated days until next purchase should be sorted alphabetically
* Items in the different states should be visually distinct
* Items in the different states should be described distinctly when read by a screen reader

**Comment by laurenmbeatty** [comment]
I'm not sure if you will need aria-labels, or not.

**Comment by laurenmbeatty** [comment]
Wave browser plugin: https://wave.webaim.org/extension/
For the last AC, check here: https://www.w3.org/TR/WCAG20-TECHS/ARIA6.html

Also, lodash is one of my favorite utility libraries. They have some handy `sortBy` and `orderBy` functionality that might be useful. https://lodash.com/docs/4.17.15

**Comment by dkimlim** [comment]
- turn li into table
- aria
- sorting with nextPurchaseDate and alphabetically

**Comment by dkimlim** [comment]
- [x] - make shoppingListItemInput into its own component
- [x] - change li into table
- [x] - build sorting arrays, then apply .sort on each 
- [x] - helper function in useEffect getShoppingList to sort items alphabetically

**Comment by AshlingH** [comment]
Here is a little screenreader example, not sure if you guys can access it http://udacity.github.io/ud891/lesson3-semantics-built-in/05-writing-semantic-html/

I was also going to point you to Laurens links above!

**Comment by dkimlim** [comment]
https://reactjs.org/docs/accessibility.html

Accessing screen reader on Mac: Command + fn + F5
