### ISSUE TITLE
14. As a user, I want the welcome screen to look pretty

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-5-smart-shopping-list#15]
AC:

* The welcome screen (the screen a user sees before they’ve created their list) looks something like the following (or equivalent, use your creativity!):

![welcome-screen](https://user-images.githubusercontent.com/4306/68095346-759abe80-fe5d-11e9-8c9f-22879fbad048.png)

**Comment by laurenmbeatty** [comment]
Maybe hide the ShoppingList and AddItem buttons on the home page. Make sure that any changes that are made to the home screen, don't negatively impact the other screens.

**Comment by dkimlim** [comment]
- [x] Move Footertabs out of Home.js and into App.js
- [x] Add Header that permeates throughout home and app "Smart Shopping List"
- [x] Move join list into its own page
- [x] CSS changes

**Comment by dkimlim** [comment]
- [ ] CSS of JoinList page
- [ ]  Mobile?
