### ISSUE TITLE
1. As a component, I want to be able to read from and write to the Firestore database

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-5-smart-shopping-list#2]
This is 1 of 2 stories that should be finished in the first week in order to enable further development.

AC:

* The following have been added as project dependencies: firebase & react-firestore
* Make a change in the Firestore database and it shows up in the app
* Make a change in the app and it shows up in the Firestore database

**Comment by jendevelops** [comment]
Jennifer and Ashling are unfamiliar with Firebase, so the tentative schedule is:

March 9, 2020 (Mon): Read documentation
March 10, 2020 (Tue) 6PM+: Pair program together to work on issue

After the pair programming session on Tuesday, we will update the issue with any future meetings/ notes

**Comment by jendevelops** [comment]
[Documentation for Adding Firebase to a JS Project](https://firebase.google.com/docs/web/setup)

**Comment by joeylaguna** [comment]
Looking forward to seeing what comes out of the Tuesday pairing session! 😄

**Comment by jendevelops** [comment]
### Documentation for Reading/Writing Data in Firestore
[Structure Data](https://firebase.google.com/docs/firestore/manage-data/structure-data)
[Add Data](https://firebase.google.com/docs/firestore/manage-data/add-data)
[Read Data](https://firebase.google.com/docs/firestore/query-data/get-data)
[Querying and Limiting Data](https://firebase.google.com/docs/firestore/query-data/order-limit-data)

**Comment by laurenmbeatty** [comment]
Here’s a good article on useEffect: https://www.robinwieruch.de/react-hooks-fetch-data
