### ISSUE TITLE
2. As a user, I want to be able to navigate between the “list” view and the “add an item” view

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-5-smart-shopping-list#4]
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.

AC:

* `react-router-dom` has been added as a project dependency
* 2 tabs are present and persistent at the bottom of the app: one for the “list” view, the other for the “add an item” view
* When a link is clicked, the browser URL updates to represent the current view
* Whichever tab is selected should indicate somehow that it is selected

**Comment by jonbascos** [comment]
Going to be meeting up On Tuesday and Wednesday to tackle the issues.

**Comment by dkimlim** [comment]
- react-router-dom has been added as a project dependency: https://reacttraining.com/react-router/web/guides/quick-start. The 1st example is for basic routing

**Comment by dkimlim** [comment]
<img width="1096" alt="Screen Shot 2020-03-10 at 10 23 31 PM" src="https://user-images.githubusercontent.com/33106448/76376427-a369a580-631e-11ea-87b7-d360cad816ae.png">
^ when installing the react-router-dom through npm there were 38k vulnerabilities detected. We performed a npm audit fix. Not sure how many vulnerabilities are left.

**Comment by laurenmbeatty** [comment]
Nice! For this project, I don't think you need to worry about those kinds of vulnerabilities. In a production app, definitely. @stacietaylorcima can confirm for me, but I don't think that's a big deal for our purposes.
