### ISSUE TITLE
Make it Pretty!

### ISSUE THREAD

**Issue by jendevelops** [the-collab-lab/tcl-5-smart-shopping-list#46]
Last updated 4/29/2020
- individually work on tasks
- meet up Saturday, 5/2/2020 to 
  - merge all branches into one make-it-pretty branch
  - make one PR into master after merges

# *AC:*
Includes acceptance criteria from issues #16 #17  #18 

All work on branch name *make-it-pretty*

## App Wide 
- [x] CSS Naming conventions 
  - @AshlingH @dkimlim @jendevelops @jonbascos  
- [ ] Creating a color constants
  - @AshlingH @dkimlim @jendevelops @jonbascos 
- [ ] Button templates for common button types 
  

## Add Item Form 
@AshlingH 
Branch: make-it-pretty-form

- [ ] Success message upon submit 
  - Set timeout (one second?), Success! + celebration emoji
  - Update Modal to include type "addSuccess"
- [ ] Refactor to use constants

## Shopping List 
@dkimlim 
Branch: make-it-pretty-list-dk
- [ ] A little something on the bottom to signify end of list
- [ ] Nicer time frame tags
- [ ] success message when checked as “bought” (strikethrough, greyed out zone, quick animation?)

@jendevelops 
Branch: make-it-pretty-list-jvb
- [ ] Fix empty list layout or bring it to homepage as a "how it works" Modal
- [ ] Add a text somewhere that displays the token for the user to share with someone else.
i.e. “To share this shopping list with someone else, use the code faust lamar uptake ” or reveal token button/ hide token button
- [ ]  labels for each shopping list columns

## Item Detail
@AshlingH 
Branch: make-it-pretty-form
- [ ] update CSS to look pretty
- [ ]  delete button modal

## Footer Tabs
@jonbascos 

branch: make-it-pretty-jb

- [x] Fix position of "View Shopping List" and "Add Item"

## Search Bar
@jonbascos 

branch: make-it-pretty-jb

- [x] Update look

## Header
@dkimlim 
Branch: make-it-pretty-list-dk
- [ ] Update logo

<hr>

# *Stretch Goals:*
- [ ] Greyscale Mode Toggle Button 
  - @jendevelops @dkimlim 
- [ ] making the color constant file dynamic based on some other js function
- [ ] Convert app to utilize [Context](https://reactjs.org/docs/context.html)
- [ ] Can change background, color scheme changes dynamically based on image
  - @jendevelops | Branch: make-it-pretty-unsplash
- [ ] Choose background photos from [Unsplash](https://unsplash.com/developers) 
  - @jendevelops | Branch: make-it-pretty-unsplash
- [ ] Choose a background from [Unsplash](https://unsplash.com/developers) based on the token keywords 
  - @jendevelops | Branch: make-it-pretty-unsplash
- [ ] Being able to change "category" that changes the image in Item Detail
- [ ] Adding a random gif based on the item name  @dkimlim 
- [ CANCELED ] Utilize [Emotion](https://emotion.sh/docs/introduction) for CSS styling 
  - @AshlingH @dkimlim @jendevelops @jonbascos  
- [ ]  blur out background and center modals

**Comment by jendevelops** [comment]
Tentatively to be worked on together Tuesday, 4/28/2020
>  ## App Wide 
> - [ ] Utilize [Emotion](https://emotion.sh/docs/introduction) for CSS styling @AshlingH @dkimlim @jendevelops @jonbascos  
> - [ ] Greyscale Mode Toggle Button @jendevelops @dkimlim 
> - [ ] Creating a color constant file  @AshlingH @dkimlim @jendevelops @jonbascos 
> - [ ] Button templates for common button types @AshlingH @jonbascos

**Comment by dkimlim** [comment]
UI changes for shopping list (added checkbox to task description)

- Add a text somewhere that displays the token for the user to share with someone else. 
i.e. “To share this shopping list with someone else, use the code `faust lamar uptake` ”
- delete button modal under search?
- success message when checked as “bought” (strikethrough, greyed out zone, quick animation?)
- labels for shopping list columns

**Comment by dkimlim** [comment]
Inspiration images: 
![to-do-list_4x](https://user-images.githubusercontent.com/33106448/80436646-9a806380-88cd-11ea-985e-f4c6ffae515f.jpg)
![5656b3f5f2c4ae18eee60148adac02ee](https://user-images.githubusercontent.com/33106448/80436650-9bb19080-88cd-11ea-9c8a-c8d937f00e25.png)
![shoppinglist-app](https://user-images.githubusercontent.com/33106448/80436654-9ce2bd80-88cd-11ea-8ea1-ef1501edeed0.png)
![android-grocery-list-app-](https://user-images.githubusercontent.com/33106448/80436655-9ce2bd80-88cd-11ea-9ee0-f1bf7181b5b8.png)
<img width="597" alt="Screen Shot 2020-04-27 at 7 17 23 PM" src="https://user-images.githubusercontent.com/33106448/80448454-5d769a00-88ea-11ea-8709-cc87ff71edd5.png">
