### ISSUE TITLE
4. As a user, I want to add a new item to my shopping list

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-5-smart-shopping-list#5]
A shopping list item consists of the following data points:

* Name of item
* How soon are you likely to buy it again?
  * Soon (in the next 7 days)
  * Kind of soon (in the next 14 days)
  * Not soon (in the next 30 days)
* Last purchased date

AC:

* User is presented with a form that allows them to enter the name of the item and select how soon they anticipate needing to buy it again (Soon, Kind of soon, Not soon)
* When the user submits the form, the item is saved to the database, associated with the user’s token
* Along with the item name, an integer corresponding to the estimated number of days until next purchase is saved: 7 for “Soon”, 14 for “Kind of soon”, and 30 for “Not soon”
* The last purchased date should be set to `null` initially (i.e. you can create an item without purchasing it)

**Comment by dkimlim** [comment]
**1) what can we do without the other team?**
- create form in addItem page, set up in firebase a dummy ShoppingList with placeholder data (shoppinglist ref, token) which will change depending on other team. 

**2) what do we need from the other team?**
- collaborate how they're going to create collections and the data structure of their nesting. 


Checking if shopping list exists: stretch goal out of scope. easier to create dummy data shopping list. STICK TO SCOPE!! :)

**Comment by AshlingH** [comment]
Nice! Very to the point! Will familiarize myself with created a form and also get a better handle on firebase

**Comment by dkimlim** [comment]
No problem. I'm also going to need to do some research! I'll leave any documentations and articles I find :) or slack them in the thread

**Comment by dkimlim** [comment]
Forms with validation with library react hook form (also has 2 other libraries on the page): https://react-hook-form.com/
install: https://react-hook-form.com/get-started

**Comment by dkimlim** [comment]
npm package for uuid: https://www.npmjs.com/package/uuid

in id schema, as suggested by Jen
