### ISSUE TITLE
8. As a user, I want to mark an item on my shopping list as purchased

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-5-smart-shopping-list#9]
AC:

* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)

**Comment by dkimlim** [comment]
- Add field associated with each item (true/false or date) whether it was purchased, with expiration of 24 hours. After expiration, turns true to false.
- change list UI to checkbox
- how to check 24 hours in db? 
- timer?

**Comment by dkimlim** [comment]
https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot

**Comment by dkimlim** [comment]
https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot
https://firebase.google.com/docs/reference/js/firebase.database.Query
https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp
https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot

**Comment by dkimlim** [comment]
- change ul li to form with input checkbox
- timestamp? handlechange
- when shoppingList loads, check all checked items for timestamp
